// <auto-generated />
using DataLogic.Weapons;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLogic.Migrations
{
    [DbContext(typeof(WeaponDataContext))]
    [Migration("20261003214001_UpdatedModelNaming")]
    partial class UpdatedModelNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataLogic.Weapons.Models.WeaponDamage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Blast")
                        .HasColumnType("int");

                    b.Property<int>("Cold")
                        .HasColumnType("int");

                    b.Property<int>("Corrosive")
                        .HasColumnType("int");

                    b.Property<int>("Electricity")
                        .HasColumnType("int");

                    b.Property<int>("EnergyDrain")
                        .HasColumnType("int");

                    b.Property<int>("Gas")
                        .HasColumnType("int");

                    b.Property<int>("HealthDrain")
                        .HasColumnType("int");

                    b.Property<int>("Heat")
                        .HasColumnType("int");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<int>("Magnetic")
                        .HasColumnType("int");

                    b.Property<float>("Puncture")
                        .HasColumnType("real");

                    b.Property<int>("Radiation")
                        .HasColumnType("int");

                    b.Property<int>("ShieldDrain")
                        .HasColumnType("int");

                    b.Property<float>("Slash")
                        .HasColumnType("real");

                    b.Property<int>("Tau")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Toxin")
                        .HasColumnType("int");

                    b.Property<int>("True")
                        .HasColumnType("int");

                    b.Property<int>("Viral")
                        .HasColumnType("int");

                    b.Property<int>("Void")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeaponDamage");
                });

            modelBuilder.Entity("DataLogic.Weapons.Models.WeaponStatsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Accuracy")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("CriticalChance")
                        .HasColumnType("real");

                    b.Property<float>("CriticalMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("DamageId")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("DamagePerShot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Disposition")
                        .HasColumnType("int");

                    b.Property<string>("ExilusPolarity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("FireRate")
                        .HasColumnType("real");

                    b.Property<bool>("IsPrime")
                        .HasColumnType("bit");

                    b.Property<int>("MagazineSize")
                        .HasColumnType("int");

                    b.Property<int>("MasteryReq")
                        .HasColumnType("int");

                    b.Property<int>("Multishot")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OmegaAttenuation")
                        .HasColumnType("real");

                    b.PrimitiveCollection<string>("Polarities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProcChance")
                        .HasColumnType("real");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReloadTime")
                        .HasColumnType("int");

                    b.Property<int>("TotalDamage")
                        .HasColumnType("int");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DamageId");

                    b.ToTable("WeaponStats");
                });

            modelBuilder.Entity("DataLogic.Weapons.Models.WeaponStatsModel", b =>
                {
                    b.HasOne("DataLogic.Weapons.Models.WeaponDamage", "Damage")
                        .WithMany()
                        .HasForeignKey("DamageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Damage");
                });
#pragma warning restore 612, 618
        }
    }
}
